# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('type', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=50),
        ),
    ]
